### ISSUE TITLE
Please define `PY_SSIZE_T_CLEAN`

### ISSUE THREAD

**Issue by methane** [PacktPublishing/Expert-Python-Programming-Fourth-Edition#2]
https://github.com/PacktPublishing/Expert-Python-Programming-Fourth-Edition./blob/ba386da307804d559a279d4cd0eaa76041e3c318/Chapter%209/02%20-%20Pure%20C%20extensions/fibonacci.c#L1

Please `#define PY_SSIZE_T_CLEAN` before `#include <Python.h>`.

See https://docs.python.org/3.10/c-api/arg.html#strings-and-buffers

> Note For all # variants of formats (s#, y#, etc.), the macro PY_SSIZE_T_CLEAN must be defined before including Python.h. On Python 3.9 and older, the type of the length argument is Py_ssize_t if the PY_SSIZE_T_CLEAN macro is defined, or int otherwise.

Your sample code doesn't use '#' format so it is not mandatory. But "define `PY_SSIZE_T_CLEAN` always" is good advice for new extension authors.

**Comment by swistakm** [comment]
Thanks for catching this!
