### ISSUE TITLE
Cannot Clone Repository

### ISSUE THREAD

**Issue by carltyndall** [PacktPublishing/Expert-Python-Programming-Fourth-Edition#3]
Cannot Clone Repository from this location.
Also if I fork the repository. I cannot clone it from the fork location.

**Comment by swistakm** [comment]
Can you post the `git` command that you use together with the output?

**Comment by Carl-Ty** [comment]
I tried cloning using GitHub desktop and PyCharm Community Edition Open from VCS.
![PycharmCummunityEditionMessage](https://user-images.githubusercontent.com/16804376/120207806-b85f7c80-c1e1-11eb-9a3d-3e839d01f7d5.png)
![GitHubDesktopMessage](https://user-images.githubusercontent.com/16804376/120207807-b8f81300-c1e1-11eb-8bca-58afa3c0fcd4.png)

**Comment by carltyndall** [comment]
The failure to clone to a windows system is due to a colon in this path
Expert-Python-Programming-Fourth-Edition/Chapter 5/01 - A bit of history: zope.interface/
Fixing the path does not eliminate the problem. Git's history also contains the path. That is why the clone actually fails in the .git directory.
For Windows, therefore, download the zip file and create a local repository.
